services:
  # Couche 1 : Stockage
  mariadb:
    image: mariadb:10.6
    container_name: dq_mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=data_quality_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - dq_network

  # Couche 2 : Exploration
  jupyter:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: dq_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks  # Mes sauvegardes
      - ./data:/home/jovyan/work/data            # Mes données brutes
    environment:
      - JUPYTER_TOKEN=admin  # Mot de passe simple pour le dev
    depends_on:
      - mariadb
    networks:
      - dq_network

    # Couche 3 Validation - Great Expectations (Port 8080)
  quality-gate:
    image: python:3.9-slim
    container_name: dq_great_expectation
    working_dir: /report
    volumes:
      - ./notebooks/mon_rapport_gx_final:/report
    command: python -m http.server 8080
    ports:
      - "8080:8080"
    networks:
      - dq_network

  # Couche 4 : Visualisation - Apache Superset (Port 8088)
  superset:
    image: apache/superset
    container_name: dq_superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=mysecretkey
    command: /usr/bin/run-server.sh
    depends_on:
      - mariadb
    networks:
      - dq_network

volumes:
  mariadb_data:

networks:
  dq_network:
    driver: bridge



